-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 13, 2021 at 09:42 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `viviendadb`
--

-- --------------------------------------------------------

--
-- Table structure for table `viviendas`
--

CREATE TABLE `viviendas` (
  `id` int(11) NOT NULL,
  `latitud` float NOT NULL,
  `longitud` float NOT NULL,
  `id_vivienda` int(11) NOT NULL,
  `titulo` mediumtext NOT NULL,
  `anunciante` mediumtext NOT NULL,
  `descripcion` longtext DEFAULT NULL,
  `reformado` tinyint(1) DEFAULT NULL,
  `telefonos` varchar(15) DEFAULT NULL,
  `tipo` varchar(512) NOT NULL,
  `precio` int(11) NOT NULL,
  `precio_metro` decimal(10,2) NOT NULL,
  `direccion` longtext NOT NULL,
  `provincia` varchar(512) NOT NULL,
  `ciudad` varchar(512) NOT NULL,
  `metros_cuadrados` int(11) NOT NULL,
  `habitaciones` int(11) DEFAULT NULL,
  `baños` int(11) NOT NULL,
  `parking` tinyint(1) DEFAULT NULL,
  `segunda_mano` tinyint(1) DEFAULT NULL,
  `armarios_empotrados` tinyint(1) DEFAULT NULL,
  `construido_en` year(4) DEFAULT NULL,
  `amueblado` tinyint(1) DEFAULT NULL,
  `calefaccion_individual` varchar(512) DEFAULT NULL,
  `calefaccion_energetica` varchar(512) DEFAULT NULL,
  `planta` int(11) DEFAULT NULL,
  `exterior` tinyint(1) DEFAULT NULL,
  `interior` tinyint(1) DEFAULT NULL,
  `ascensor` tinyint(1) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `calle` varchar(512) DEFAULT NULL,
  `barrio` varchar(512) DEFAULT NULL,
  `distrito` varchar(512) DEFAULT NULL,
  `terraza` tinyint(1) DEFAULT NULL,
  `trastero` tinyint(1) DEFAULT NULL,
  `cocina_equipada` tinyint(1) DEFAULT NULL,
  `cocina_equipada2` tinyint(1) DEFAULT NULL,
  `aire_acondicionado` tinyint(1) DEFAULT NULL,
  `piscina` tinyint(1) DEFAULT NULL,
  `jardin` tinyint(1) DEFAULT NULL,
  `metros_cuadrados_utiles` int(11) DEFAULT NULL,
  `movilidad_reducida` tinyint(1) DEFAULT NULL,
  `plantas` int(11) DEFAULT NULL,
  `mascotas` tinyint(1) DEFAULT NULL,
  `balcon` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `viviendas`
--

INSERT INTO `viviendas` (`id`, `latitud`, `longitud`, `id_vivienda`, `titulo`, `anunciante`, `descripcion`, `reformado`, `telefonos`, `tipo`, `precio`, `precio_metro`, `direccion`, `provincia`, `ciudad`, `metros_cuadrados`, `habitaciones`, `baños`, `parking`, `segunda_mano`, `armarios_empotrados`, `construido_en`, `amueblado`, `calefaccion_individual`, `calefaccion_energetica`, `planta`, `exterior`, `interior`, `ascensor`, `fecha`, `calle`, `barrio`, `distrito`, `terraza`, `trastero`, `cocina_equipada`, `cocina_equipada2`, `aire_acondicionado`, `piscina`, `jardin`, `metros_cuadrados_utiles`, `movilidad_reducida`, `plantas`, `mascotas`, `balcon`) VALUES
(106, 40.3658, -3.58845, 84099521, 'Alquiler de Piso en calle Juan Antonio Rebolledo y Palma, 20', 'Profesional   Lazora Alquiler', '\"¡Alquila ahora y llévate el primer mes gratis!Vivienda de 2 dormitorios en emblemático edificio de diseño situado en el PAU de Vallecas, galardonado con un conocido premio de arquitectura.Sorprenden sus espectaculares y luminosos portales, de cuidado diseño. Un amplio espacio cubierto, con asientos, en el que disfrutar de la vida vecinal.El edificio cuenta con sistema de video-vigilancia y conserjería particular. En las primeras plantas del edificio las viviendas son tipo dúplex. Además, todas las viviendas disponen de una plaza de garaje.Se encuentra en una zona completamente consolidada con todo tipo de servicios, al lado del Centro Comercial La Gavia, la estación de Metro Valdecarros y a tan sólo 100 metros de Mercadona. Salida directa a la A-3.VIVIENDAS ACABADO ESTÁNDAR.VIVIENDA NO AMUEBLADA, LAS IMÁGENES PERTENECEN A VIVIENDA PILOTO SIN CARÁCTER CONTRACTUAL.Precio desde: 779€/mesREQUISITOSSeguro de impago.En la firma de contrato se solicitará un seguro de vivienda (sobre contenido).Aportación de 3 últimas nóminas o similar para acreditar ratio de solvencia.Antigüedad laboral exigible mínimo 1 año.\"', 0, '917 222 011', 'piso', 779, '12.98', 'Calle Juan Antonio Rebolledo y Palma, 20, Urb. Edificio Vallecas II, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 60, 2, 1, 0, 0, 0, 2009, 0, 'gas natural', '', 17, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(107, 40.3658, -3.58845, 84099521, 'Alquiler de Piso en calle Juan Antonio Rebolledo y Palma, 20', 'Profesional   Lazora Alquiler', '\"¡Alquila ahora y llévate el primer mes gratis!Vivienda de 2 dormitorios en emblemático edificio de diseño situado en el PAU de Vallecas, galardonado con un conocido premio de arquitectura.Sorprenden sus espectaculares y luminosos portales, de cuidado diseño. Un amplio espacio cubierto, con asientos, en el que disfrutar de la vida vecinal.El edificio cuenta con sistema de video-vigilancia y conserjería particular. En las primeras plantas del edificio las viviendas son tipo dúplex. Además, todas las viviendas disponen de una plaza de garaje.Se encuentra en una zona completamente consolidada con todo tipo de servicios, al lado del Centro Comercial La Gavia, la estación de Metro Valdecarros y a tan sólo 100 metros de Mercadona. Salida directa a la A-3.VIVIENDAS ACABADO ESTÁNDAR.VIVIENDA NO AMUEBLADA, LAS IMÁGENES PERTENECEN A VIVIENDA PILOTO SIN CARÁCTER CONTRACTUAL.Precio desde: 779€/mesREQUISITOSSeguro de impago.En la firma de contrato se solicitará un seguro de vivienda (sobre contenido).Aportación de 3 últimas nóminas o similar para acreditar ratio de solvencia.Antigüedad laboral exigible mínimo 1 año.\"', 0, '917 222 011', 'piso', 779, '12.98', 'Calle Juan Antonio Rebolledo y Palma, 20, Urb. Edificio Vallecas II, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 60, 2, 1, 0, 0, 0, 2009, 0, 'gas natural', '', 17, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(108, 40.3622, -3.5936, 87104447, 'Alquiler de Piso en LAS SUERTES', 'Profesional   MIRIAM .', '\"\"-LAS SUERTES/ VALDECARROS- Piso de 76m², exterior, sin amueblar y para entrar a vivir. La vivienda consta de salón, terraza cerrada, tres dormitorios, armarios empotrados, dos cuartos baño y cocina amueblada y equipada con electrodomésticos. Dispone de ascensor, plaza de garaje, trastero, conserje y piscina. Calefacción y agua caliente individual por gas natural. Aire acondicionado. Puerta blindada y suelo de gres. Transporte público más cercano línea de Metro Valdecarros y líneas de autobús, 142, 145 y N9. El inmueble se encuentra rodeado de todo tipo de servicios y comercios incluyendo el Centro Comercial La Gavia. Gastos de comunidad incluidos en el precio. SIN COMISIÓN DE AGENCIA. \".\"', 0, '608 982 823', 'piso', 1000, '13.16', 'LAS SUERTES, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 76, 3, 2, 0, 0, 0, 0000, 0, 'gas natural', 'en trámite', 1, 0, 0, 0, '2019-09-26', 'LAS SUERTES', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(109, 40.373, -3.60765, 84071124, 'Alquiler de Piso en calle Corral de Almaguer, Madrid, 12', 'Profesional   Lazora Alquiler', '\"Todas las estancias son independientes, cuenta con calefacción en toda la casa y A/A mediante rejilla en salón y dormitorio. Armarios empotrados.Suelos de tarima.Próximo a la Parroquia de Santa María Josefa del Corazón de Jesús y al Colegio Stella Maris La Gavia.Finca con apenas 10 años de vida, año 2008, dispone de piscina, zona infantil, zonas verdes y conserje.Está situado en una zona muy tranquila rodeado de calles peatonales, cercano a todo tipo de comercios y servicios, próximo a la Parroquia de Santa María Josefa del Corazón de Jesús y al Colegio Stella Maris La Gavia.Muy bien ubicado, a 650 metros de la estación de metro La Gavia (línea 1 conexión directa con el centro de Madrid), líneas regulares de autobuses y fácil acceso a principales carreteras de la Comunidad de Madrid A-3, M-45 Y M-40.Consulte condiciones y disponibilidad. Sin comisiones de agencia.Precio desde: 705€/mesREQUISITOSLibre1 mes de fianzaSeguro de impagoSeguro de vivienda a la firma contrato (contenido)Aportación de 3 últimas nóminas o similar para acreditar ratio de solvencia.\"', 0, '917 222 011', 'piso', 705, '17.62', 'Calle Corral de Almaguer, Madrid, 12, Urb. Lazora Vallecas III, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 40, 0, 1, 0, 0, 0, 2008, 0, 'bomba de frío/calor', 'en trámite', 3, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(110, 40.3628, -3.59207, 33810793, 'Alquiler de Piso en avenida de las suertes, 98', 'Profesional   Promociones Urbanas Sl', '\"ABSTENERSE PERSONAS SIN MINUSVALIA.Vivienda TOTALMENTE ADAPTADA A personas de movilidad reducida, en edifio de viviendas de alquiler en régimen protegido (VPPB). Urbanización cerrada con zonas comunes ajardinadas y área de juegos infantiles.Muy bien comunicado, a menos de 5 minutos andando de la parada de metro “Valdecarros”, junto a las líneas de autobús 142, 145 y N9; a 10 min. del C. C. La Gavia, Carrefour e Ikea, frente a Mercadona y cerca de colegios.La vivienda tiene 77, 05 m2 útiles, repartidos en cocina con tendedero, salón, dos dormitorios, y dos baños, uno de ellos totalmente adaptado con plato de ducha a nivel y barras de apoyo tanto en ducha como en inodoro. La cocina está totalmente adaptada y cuenta con vitrocerámica y campana extractora y horno. Armarios empotrados. Dispone de un sistema de aerotermia (Altherma de Daikin con calificación energética de A++) que proporciona aire frío, caliente y acs, .NO SE ADMITEN ANIMALES. El precio INCLUYE GASTOS DE COMUNIDAD, IBI, PLAZA DE GARAJE Y TRASTERO.Condiciones para poder alquilar: *No tener propiedades en la Comunidad de Madrid; a nivel nacional no tener propiedad en régimen protegido.*No superar en ingresos el 2.5 veces el Iprem.NO SE ADMITEN ANIMALES.Se hará estudio de solvencia económica.\"', 0, '914 891 820', 'piso', 689, '6.89', 'Avenida de las suertes, 98, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 100, 2, 2, 0, 0, 0, 2015, 0, 'TRUE', '', 0, 0, 0, 0, '2019-10-02', 'Avenida de las suertes, 98', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 77, 0, 0, 0, 0),
(111, 40.3676, -3.60157, 84200113, 'Alquiler de Piso en calle José Gutiérrez Maroto, 3', 'Profesional   Viviendas en alquiler', '\"¡Alquila ahora y llévate el primer mes gratis! Oferta válida hasta el 31.10. 2019Vivienda de 2 dormitorios y un baño completo. Incluye plaza de garaje y trastero.Situación privilegiada en la zona, estando frente al centro comercial \"la gavia\" y junto a colegio concertado \"Gredos san diego las suertes\". Con toda clase de comercios y servicios a mano, entre las dos avenidas más importantes del ensanche (avd. de las suertes y avd. ensanche de Vallecas) y totalmente accesible gracias a las carreteras m-45 y a-3. Muy cercano al metro de las suertes (l-1) y con autobús l142 y n9 (búho) a 100 metros. Consulte condiciones y disponibilidad.Sin comisiones de agencia. REQUISITOS1 mes de fianza.Seguro de impago.Seguro de hogar a la firma de contrato (contenido).Aportación de contrato de trabajo o similar (1 año de antigüedad mínimo) y 3 últimas nóminas para acreditar ratio de solvencia.\"', 0, '917 222 013', 'piso', 800, '11.76', 'Calle José Gutiérrez Maroto, 3, Urb. Edificio Vallecas 62, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 68, 2, 1, 0, 0, 0, 0000, 0, 'gas natural', 'en trámite', 1, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(112, 40.366, -3.62052, 87037099, 'Alquiler de Piso en Ensanche de Vallecas - La Gavia', 'Profesional   Inmobiliaria', '\"Ref 4736.   Bonito apartamento seminuevo construido en 2008.   Vivienda ubicada en el Ensanche de Vallecas, en urbanización privada con portero físico y piscina. Se distribuye en un dormitorio que incorpora un cuarto de baño con plato de ducha, salón comedor, cocina amueblada e independiente. Calidades: puerta de entrada blindada, puertas interiores en roble, cerramientos exteriores con ventanas de aluminio tipo climalit, suelos de tarima. Calefacción por gas natural y aire acondicionado con bomba de calor por conductos en toda la casa. En el precio está incluida una plaza de garaje muy amplia (ver foto) y trastero. La vivienda se ubica en la séptima planta del edificio, por lo que tiene muy buenas vistas. Zona muy tranquila y muy bien comunicado con transporte, tanto público como privado. LLÁMENOS al TELÉFONO 91 332 42 00. OFICINA en SIERRA DE GADOR 33 en Villa de Vallecas.  .\"', 0, '911 363 142', 'piso', 750, '20.27', ', Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 37, 0, 1, 0, 0, 0, 2009, 0, 'TRUE', '', 7, 0, 0, 0, '2019-09-24', '', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0),
(113, 40.364, -3.5978, 83588933, 'Alquiler de Piso en avenida del Ensanche de Vallecas', 'Profesional   Viviendas en alquiler', '\"¡Alquila ahora y llévate el primer mes gratis!Oferta válida hasta el 31/10/2019Válido sólo para familia numerosa.Situada en plena Avenida del Ensanche de Vallecas, con todo tipo de servicios a su alcance.Vivienda de 5 dormitorios que cuenta con dos baños.Cocina amueblada y semi equipada (campana, horno y vitrocerámica).Situada en plena Avenida del Ensanche de Vallecas, con todo tipo de servicios a su alcance y perfectamente comunicadas con acceso directo a la a-3 y muy próxima a la m-40 y m-45.Autobuses en la misma puerta, l145 y n9 (búho) y parada de metro \"las suertes\" a 200m. a escasos 5 minutos del centro comercial \"la gavia\" e ikea, así como de supermercados como mercadona, farmacia, bancos y todo tipo de comercios. Además cuenta con amplia oferta educativa, teniendo el colegio bilingüe Loyola de Palacios a mano, escuelas infantiles y zonas de ocio con parques, carril bici y pista de patinaje.Consulte condiciones y disponibilidad.Sin comisiones de agencia. Las imágenes publicitadas corresponden a la vivienda piloto, sin carácter contractual.REQUISITOS VPPAIngresos en 2018 no superiores a 51.254€.Estar empadronado en cualquier municipio de la CAM.No tener vivienda en propiedad.1 mes de fianza + Seguro de impago.Seguro de hogar a la firma de contrato (contenido).Aportación de 3 últimas nóminas o contrato de trabajo para acreditar ratio de solvencia.Carnet de Familia Numerosa.\"', 0, '917 222 013', 'piso', 900, '7.83', 'Avenida del Ensanche de Vallecas, Urb. Edificio Vallecas 115, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 115, 5, 2, 0, 0, 0, 2006, 0, 'gas natural', '', 0, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(114, 40.3591, -3.59804, 35133364, 'Alquiler de Chalet adosado en calle Embalse de Manzanares, 60', 'Particular    Alquiler', '\"ABSTENERSE AGENCIAS.Disponible para visitas a partir de Noviembre 2019.Propietario particular, por lo que no se cobra comisión de agencia. -Vivienda unifamiliar adosada del año 2011 con 4 dormitorios y dos baños ubicada en urbanización cerrada de 20 viviendas unifamiliares. Se alquila sin amueblar excepto la cocina que está completamente equipada.-Distribución:Planta baja: Porche, entrada, salón, cocina y cuarto trastero. Primera planta: 4 dormitorios, dos de ellos dobles, 2 baños y 2 terrazas.Segunda planta (Azotea): Terraza descubierta de 60 metros cuadrados.Total: 142 metros cuadrados útiles más 60 metros de solarium - azotea.-Cocina amueblada con electrodomésticos de primeras marcas (Siemens, Fagor), muebles de estilo moderno y encimera Silestone de 4 metros.-Cuenta con rejas de seguridad en todas las ventanas de la vivienda y puerta principal blindada-Sistema individual de placas solares para el agua caliente de aporte adicional al gas natural (Gran ahorro energético). Incluido en precio del alquiler el mantenimiento de este sistema.-1 plaza de garaje en el parking comunitario subterráneo incluida en el precio. El acceso al parking no es directo desde la vivienda. Se accede desde la urbanización por una entrada con escalera o por otra entrada con rampa.-Integrado en parcela comunitaria con jardines. La vivienda no tiene parcela independiente. La urbanización no tiene piscina comunitaria. Puede instalarse piscina portátil en la terraza de la azotea.La comunidad cuenta con cámaras de vigilancia en urbanización y garaje.-Ubicado en Pau de Vallecas, a 5 minutos andando del metro Valdecarros (Línea 1) y a 15 minutos andando del Centro Comercial La Gavia - IKEA. Varios supermercados Mercadona y Ahorramas en las inmediaciones. Colegio Loyola del Palacio enfrente de a la vivienda. Gastos de comunidad de vivienda y plaza de garaje, Impuesto de Bienes Inmuebles (IBI), seguro de la vivienda y mantenimiento de caldera y placas solares incluidos en el precio.Se requerirá acreditar solvencia económica mediante contrato de trabajo, nominas, etc.\"', 0, '', 'chalet', 1400, '6.36', 'Calle Embalse de Manzanares, 60, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 220, 4, 2, 0, 0, 0, 0000, 0, 'gas natural', '', 0, 0, 0, 0, '2019-10-01', 'Calle Embalse de Manzanares, 60', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 142, 0, 3, 0, 0),
(115, 40.3607, -3.59795, 86302049, 'Alquiler de Piso en calle Antonio Gades, 54', 'Profesional   Viviendas en alquiler', '\"¡Alquila ahora y llévate el primer mes gratis!Oferta válida hasta el 31/10/2019Vivienda de 5 dormitorios destinada a familia numerosa. Urbanización privada que cuenta con conserje y amplias zonas comunes con parque infantil. Una de las calles con más relevancia del PAU de Vallecas. Promoción construida en el año 2007. Cocina amueblada y semi equipada con campana, horno y vitrocerámica. Suelos de grés y armarios empotrados. Dispone de una plaza de garaje.   Zona totalmente consolidada con todos los servicios educativos, sanitarios, supermercados, rodeado de parques, zonas verdes, zonas de ocio en el Centro Comercial La Gavia. Perfectamente comunicado; transporte público línea 1 de Metro (junto al metro las Suertes), autobús líneas 142 - 145 y acceso por carretera desde la M-45 y A-3 y con fácil acceso a la M-40 y M-50.Consulte condiciones y disponibilidad.Sin comisiones de agencia.Vivienda no amueblada.Requisitos (VPPA)Ingresos familiares en 2018 que no excedan de 5,5 veces el IPREM (51.254€).Estar empadronado en cualquier municipio de la CAM.Estar inscrito en la lista única de demandantes.No tener vivienda en propiedad.Acreditar mediante carnet, familia numerosa. Garantías1 MES DE FIANZA + SEGURO DE IMPAGO Seguro de vivienda (contenido)Aportación 3 últimas nóminas o contrato de trabajo para acreditar ratio de solvencia.\"', 0, '917 222 013', 'piso', 990, '7.62', 'Calle Antonio Gades, 54, Urb. Edificio Vallecas 66, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 130, 5, 2, 0, 0, 0, 2007, 0, 'gas natural', 'en trámite', 0, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(116, 40.3676, -3.60932, 87126609, 'Alquiler de Piso en calle Entrepeñas, 78', 'Particular    jim', '\"Particular alquila piso muy luminoso, todo exterior, estupendas vistas, amplio, nuevo en Ensanche de Vallecas, muy cerca del metro La Gavia.Consta de 4 dormitorios con armarios empotrados, 2 baños, salón amplio, cocina con lavadora, frigorífico, horno, placa vitrocerámica y campana extractora. Parquet y ventana climalit. Con balgón. Sin muebles.Zona tranquila y segura, con piscina, conserje en la puerta y vigilancia con cámara 24h.Metro y bus cerca en la puerta.Ikea, Carrefour y Centro Comercial La Gavia enfrente. Salidas inmediatas a M45 y A3.Garaje incluidos. IBI e impuesto basura incluidos.Lo alquila directamente el dueño, sin comisión de agencia.IMPORTANTE: hablar mejor por Whatsapp 24h, llamadas a partir de 15:00 de lunes a viernes. Los fines de semana 10:00-23:00.\"', 0, '626 768 582', 'piso', 1050, '7.05', 'Calle Entrepeñas, 78, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 149, 4, 2, 0, 0, 0, 0000, 0, 'gas natural', 'no indicado', 5, 0, 0, 0, '2019-09-27', 'Calle Entrepeñas, 78', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 120, 0, 0, 0, 0),
(117, 40.361, -3.59731, 86255584, 'Alquiler de Piso en calle Antonio Gades, 44', 'Profesional   Viviendas en alquiler', '\"¡Alquila ahora y llévate el primer mes gratis! Oferta válida hasta el 31.10. 2019Vivienda de 2 dormitorios en 2ª planta; Cuenta con plaza de garaje y trastero. La urbanización tiene amplias zonas ajardinadas y está a escasos metros de la avenida principal de la zona (avd. ensanche de Vallecas). Con toda clase de comercios cercanos, así como a 5 minutos del centro comercial \"la gavia\" y a 150 metros del colegio bilingüe \"Loyola de palacios\". fácil acceso a m-45 y a-3, y autobús l145 y n9 (búho) a 100 metros. Ubicación: C/ Antonio Gades, 44 Esc, A, B, C En pleno corazón del ensanche de Vallecas, frente a supermercados como Mercadona y Ahorramás, farmacia, bancos, iglesia y ciudad deportiva del rayo vallecano. Fácil acceso a-3 y m-45, bien comunicado por autobús l145 y n9 (búho) y a 200 metros de la parada de metro \"la gavia\". Consulte condiciones y disponibilidadSin comisiones de agenciaREQUISITOSAportación de contrato de trabajo o similar y 3 últimas nóminas para acreditar ratio de solvencia.En la firma del contrato se solicitará un seguro de la vivienda.1 mes de fianza + seguro de impago.\"', 0, '917 222 013', 'piso', 790, '11.29', 'Calle Antonio Gades, 44, Urb. Edificio Vallecas II 81, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 70, 2, 1, 0, 0, 0, 0000, 0, 'gas natural', '', 2, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(118, 40.3652, -3.58318, 87167475, 'Alquiler de Estudio en calle Cerro del Murmullo, 13', 'Particular    angie', '\"se alquila por 3 meses estudio, personas responsables.\"', 0, '603 106 013', 'piso', 400, '8.00', 'Calle Cerro del Murmullo, 13, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 50, 0, 1, 0, 0, 0, 0000, 0, '', 'en trámite', 1, 0, 0, 0, '2019-10-02', 'Calle Cerro del Murmullo, 13', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(119, 40.361, -3.59731, 86255307, 'Alquiler de Piso en calle de Antonio Gades, 44', 'Profesional   Viviendas en alquiler', '\"¡Alquila ahora y llévate el primer mes gratis! Oferta válida hasta el 31.10. 2019¡SIN COMISIONES DE AGENCIA!Vivienda de 1 dormitorio en 2ª planta; Cuenta con plaza de garaje y trastero. La urbanización tiene amplias zonas ajardinadas y está a escasos metros de la avenida principal de la zona (avd. ensanche de Vallecas). Con toda clase de comercios cercanos, así como a 5 minutos del centro comercial \"la gavia\" y a 150 metros del colegio bilingüe \"Loyola de palacios\". fácil acceso a m-45 y a-3, y autobús l145 y n9 (búho) a 100 metros. Ubicación: C/ Antonio Gades, 44 Esc, A, B, C En pleno corazón del ensanche de Vallecas, frente a supermercados como Mercadona y Ahorramás, farmacia, bancos, iglesia y ciudad deportiva del rayo vallecano. Fácil acceso a-3 y m-45, bien comunicado por autobús l145 y n9 (búho) y a 200 metros de la parada de metro \"la gavia\". Consulte condiciones y disponibilidadSin comisiones de agenciaREQUISITOSAportación de contrato de trabajo o similar y 3 últimas nóminas para acreditar ratio de solvencia.En la firma del contrato se solicitará un seguro de la vivienda.1 mes de fianza + seguro de impago.\"', 0, '917 222 013', 'piso', 660, '12.22', 'Calle de Antonio Gades, 44, Urb. Edificio Vallecas II 81, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 54, 0, 1, 0, 0, 0, 0000, 0, 'gas natural', 'en trámite', 2, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(120, 40.3703, -3.61207, 87136863, 'Alquiler de Piso en avenida del Ensanche de Vallecas, 11', 'Gema', '\"Piso amueblado de 89m2 con tres habitaciones, salón/comedor muy amplio, cocina con tendedero y 2 baños. También incluye plaza de garaje muy amplía. Calefacción y agua caliente de gas natural. Sin gastos de Comunidad.Edificio sin zonas comunes muy bien comunicado. Metro, autobús y supermercados en la misma puerta. Precio: 950€/mesCondiciones:-Nos están permitidas mascotas-1 mes de fianza (950€)-Seguro de alquiler. Se solicita para su aprobación por la compañía de seguros: * 3 últimas nóminas * contrato de trabajo * DNI titulares del contrato- el pago del seguro de alquiler será a partes iguales cuando pase la liquidación la cía de seguros.\"', 0, '606 731 916', 'piso', 950, '9.13', 'Avenida del Ensanche de Vallecas, 11, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 104, 3, 2, 0, 0, 0, 0000, 0, 'gas natural', 'no indicado', 4, 0, 0, 0, '2019-09-30', 'Avenida del Ensanche de Vallecas, 11', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 89, 0, 0, 0, 0),
(121, 40.361, -3.59731, 86077641, 'Alquiler de Ático en calle Antonio Gades, 44', 'Profesional   Viviendas en alquiler', '\"¡Alquila ahora y llévate el primer mes gratis! Oferta válida hasta el 31.10. 2019¡SIN COMISIONES DE AGENCIA!Vivienda de 2 dormitorios en planta ático. Terraza de 20m². Cuenta con plaza de garaje y trastero. La urbanización tiene amplias zonas ajardinadas y está a escasos metros de la avenida principal de la zona (avd. ensanche de Vallecas). Con toda clase de comercios cercanos, así como a 5 minutos del centro comercial \"la gavia\" y a 150 metros del colegio bilingüe \"Loyola de palacios\". fácil acceso a m-45 y a-3, y autobús l145 y n9 (búho) a 100 metros. Ubicación: C/ Antonio Gades, 44 Esc, A, B, C En pleno corazón del ensanche de Vallecas, frente a supermercados como Mercadona y Ahorramás, farmacia, bancos, iglesia y ciudad deportiva del rayo vallecano. Fácil acceso a-3 y m-45, bien comunicado por autobús l145 y n9 (búho) y a 200 metros de la parada de metro \"la gavia\". Consulte condiciones y disponibilidadSin comisiones de agenciaREQUISITOSAportación de contrato de trabajo o similar y 3 últimas nóminas para acreditar ratio de solvencia.En la firma del contrato se solicitará un seguro de la vivienda.1 mes de fianza + seguro de impago.\"', 0, '917 222 013', 'piso', 965, '13.79', 'Calle Antonio Gades, 44, Urb. Edificio Vallecas II 81, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 70, 2, 1, 0, 0, 0, 0000, 0, 'gas natural', 'en trámite', 7, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(122, 40.3796, -3.63331, 87142156, 'Alquiler de Piso en calle puerto de pozazal, 37', 'Profesional   Contacto Contacto', '\"LEER TEXTO COMPLETONo pedimos AVALES bancarios, pedimos contrato de trabajo y 2 ultimas nominas, se puede entrar cualquier día del mes, desde el día que entra se pagaría cada 30 días.Se encuentra ubicado en la calle puerto de pozazal 37, en el ensanche de vallecas, metro y renfe mas cercano sierra de guadalupeAl alquiler del apartamento se le incluye: gimnasio, piscina, pádel, parque infantil, comunidad, ascensores, agua sin limitación y hasta 50 € de luz ya incluidos en el precio.Autobuses, renfe y metro sierra de Guadalupe. También tenemos en otras zonas.NO SE ADMITEN MASCOTAS.Teléfono de contacto 622843044.\"', 0, '912 173 875', 'piso', 750, '13.64', 'Calle puerto de pozazal, 37, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 55, 0, 1, 0, 0, 0, 0000, 0, 'TRUE', 'en trámite', 3, 0, 0, 0, '2019-09-30', 'Calle puerto de pozazal, 37', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(123, 40.3576, -3.59305, 85984683, 'Alquiler de Piso en calle Gran Vía del Sureste, 59 B', 'Profesional   Viviendas en alquiler', '\"¡Alquila ahora y llévate 2 meses gratis! Oferta válida hasta el 31.10. 2019Adaptada a personas con movilidad reducida.Vivienda de 2 dormitorios en urbanización cerrada, en buen estado. Consta de salón-comedor, cocina cerrada totalmente amueblada y semi equipada con vitrocerámica, campana y horno, 2 dormitorios, un baño. Dispone de armario empotrados, calefacción y agua caliente central individualizada, suelos de tarima, amplios ventanales, amplia plaza de garaje, servicio de conserjería y vigilancia física 24 horas. Muy luminoso, sin amueblar. A pocos metros de parada de autobuses y metro línea 1 (Valdecarros), cerca del centro comercial la Gavia. La zona ofrece todos los servicios necesarios. ven a visitarlo\"Consulte condiciones y disponibilidad.Sin comisiones de agencia.Las imágenes pertenecen a la vivienda piloto, sin carácter contractual.REQUISITOS DE ACCESOUn mes de fianza.Seguro de impago de rentas ( ¡sin avales ni otras garantías adicionales! ) Seguro del Hogar. Acreditar solvencia.Acreditar grado de minusvalía mediante certificado.\"', 0, '917 222 013', 'piso', 725, '9.18', 'Calle Gran Vía del Sureste, 59 B, Urb. Edificio Vallecas 289, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 79, 2, 1, 0, 0, 0, 2008, 0, 'gas natural', '', 2, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(124, 40.3622, -3.59566, 87144598, 'Alquiler de Piso en avenida del ensanche de vallecas', 'Profesional   Nuevo Hogar Inmobiliaria', '\"Estupendo y luminoso apartamento, cocina americana totalmente equipada con vista al salón, dormitorio amplio con vestidor, wc completo con plato de ducha y ventana. Altillo de 18m2, Totalmente exterior. Amueblado. Suelo de tarima, a/a con bomba de calor, garaje, piscina, conserje y vigilancia 24h. Zona con todos los servicios (transporte público metro valdecarros línea 1, zonas de ocio, centro comercial la gavia ) buenos accesos con a3, m45, m50.\"', 0, '910 756 837', 'piso', 760, '13.10', 'Avenida del ensanche de vallecas, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 58, 0, 1, 0, 0, 0, 0000, 0, 'TRUE', '', 6, 0, 0, 0, '2019-09-30', 'Avenida del ensanche de vallecas', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 57, 0, 0, 0, 0),
(125, 40.3608, -3.59759, 82981255, 'Alquiler de Piso en calle Antonio Gades, 52', 'Profesional   Viviendas en alquiler', '\"DESTINADA A PERSONAS CON ALGÚN TIPO DE DISCAPACIDAD. ¡Alquila ahora y llévate el primer mes gratis!Oferta válida hasta el 31/10/2019Vivienda de tres dormitorios destinada a personas con algún tipo de discapacidad.  Urbanización privada que cuenta con conserje y amplias zonas comunes con parque infantil.  Una de las calles con más relevancia del PAU de Vallecas. Promoción construida en el año 2007. Cocina amueblada y totalmente equipada. Suelos de tarima y armarios empotrados. Dispone de una plaza de garaje.   Zona totalmente consolidada con todos los servicios educativos, sanitarios, supermercados, rodeado de parques, zonas verdes, zonas de ocio en el Centro Comercial La Gavia.  Perfectamente comunicado; transporte público línea 1 de Metro (junto al metro las Suertes), autobús líneas 142 - 145 y acceso por carretera desde la M-45 y A-3 y con fácil acceso a la M-40 y M-50.Consulte condiciones y disponibilidad.Sin comisiones de agencia.Vivienda no amueblada.Imágenes corresponden a vivienda piloto, sin carácter contractual.REQUISITOS VPPACertificado grado de minusvalía.Ingresos familiares que no excedan del 5,5 veces IPREM 2017. (51.254€).Estar empadronado en cualquier municipio de la CAM.1 mes de fianza.Seguro de impago.A la firma de contrato se solicitará un seguro de vivienda (contenido).Aportación 3 últimas nóminas o contrato de trabajo para acreditar ratio de solvencia (45% max. ).\"', 0, '917 222 013', 'piso', 840, '7.24', 'Calle Antonio Gades, 52, Urb. Edificio Vallecas 66, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 116, 3, 1, 0, 0, 0, 2007, 0, 'gas natural', '', 0, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(126, 40.3634, -3.60041, 87079777, 'Alquiler de Piso en calle Embalse de Valmayor, 41', 'Ana', '\"Junto metro Las Suertes y autobuses. A 5 min del centro comercial La Gavia.Muy luminoso. Amueblado.Salón 22m, cocina equipada con tendedero, 3 dormitorios (ppal en suite) y 2 baños. Armarios empotrados en todas las habitaciones, pasillo y entrada. Aire acondicionado. Agua y calefacción individual con Gas Natural.Plaza de garaje incluida en precio.\"', 0, '645 969 856', 'piso', 1200, '9.60', 'Calle Embalse de Valmayor, 41, Urb. Portal 7, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 125, 3, 2, 0, 0, 0, 0000, 0, 'gas natural', 'no indicado', 1, 0, 0, 0, '2019-09-30', '', '', '', 0, 0, 0, 0, 0, 0, 0, 105, 0, 0, 0, 0),
(127, 40.3711, -3.61128, 82976093, 'Alquiler de Piso en calle Villaluenga de la Sagra, Madrid, 11 B', 'Profesional   Viviendas en alquiler', '\"Vivienda destinada a familias numerosas. ¡Alquila ahora y llévate el primer mes gratis!Oferta válida hasta el 31/10/2019Vivienda de 4 dormitorios.En pleno corazón del ensanche de Vallecas, frente a supermercados como Mercadona y Ahorramás, farmacia, bancos, iglesia y ciudad deportiva del rayo vallecano. Fácil acceso a-3 y m-45, bien comunicado por autobús l145 y n9 (búho) y a 200 metros de la parada de metro \"la gavia\". Sin comisiones de agencia.Algunas de las imágenes son amueblamientos virtuales, sin carácter contractual.REQUISITOSIngresos familiares que no excedan del 5,5 veces IPREM. (51.254€).Estar empadronado en cualquier municipio de la CAM.Vivienda destinada a familias numerosas (acreditar mediante carnet).1 mes de fianzaSeguro de impago.Seguro de vivienda a la firma de contrato (contenido).Aportación 3 últimas nóminas o contrato de trabajo para acreditar ratio de solvencia.\"', 0, '917 222 013', 'piso', 900, '7.83', 'Calle Villaluenga de la Sagra, Madrid, 11 B, Urb. Edificio Vallecas 82 VPPA, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 115, 4, 2, 0, 0, 0, 0000, 0, 'gas natural', '', 1, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(128, 40.3646, -3.58875, 32941158, 'Alquiler de Piso en avenida cerro milano', 'Profesional   equipo de alquiler', '\"Apartamento exterior de 1 dormitorio en Avda Cerro Milano, con salón independiente, cocina amueblada y equipada con electrodomésticos, 1 baño completo, suelos de tarima, ventanas climalit, armarios empotrados, calefacción de gas natural, aire acondicionado por climatización. Amueblado. Finca con ascensor, piscina comunitaria, trastero. Gastos de comunidad y plaza de garaje incluidos en el precio. Metro Valdecarros y paradas de autobuses muy cercanos.\"', 0, '915 449 893', 'piso', 680, '13.60', 'Avenida cerro milano, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 50, 0, 1, 0, 0, 0, 0000, 0, 'gas natural', '', 5, 0, 0, 0, '2019-09-30', 'Avenida cerro milano', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(129, 40.3658, -3.61895, 84377746, 'Alquiler de Piso en calle la Granja de San Ildefonso, Madrid, 32', 'Profesional   Vivenio Madrid', '\"Vivienda de 1 dormitorio.Calle Granja de San Ildefonso, ubicada en el PAU DE VALLECAS, un nueva área residencial dentro de Madrid con amplias zonas verdes, parques, centros docentes, complejos deportivos, espacios sociales, un gran centro comercial y numerosas calles peatonales. Una inteligente distribución de las viviendas, aprovechando los espacios lo mejor posible. Una memoria de calidades inmejorable y sus zonas comunes, en definitiva, un lugar ideal para vivir, piscina, pista de pádel, zona de juegos infantiles, plaza de garaje y trastero. Cocina totalmente amueblada y equipada con electrodomésticos. Consulte condiciones y disponibilidad. Sin comisiones de agencia. Vivienda no amueblada, las imágenes pertenecen a la vivienda piloto, sin carácter contractual. Planta 3ª exteriorCon ascensor.REQUISITOS1 mes de fianza + 1 mes depósito + Seguro de impago.A la firma de contrato se solicitará un seguro de vivienda (contenido).Contrato indefinido de + de 1 año de antigüedad.Aportación de 3 últimas nóminas o similar para acreditar ratio de solvencia.\"', 0, '917 222 018', 'piso', 715, '13.75', 'Calle la Granja de San Ildefonso, Madrid, 32, Urb. Vivenio La Granja, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 52, 0, 1, 0, 0, 0, 2011, 0, 'gas natural', 'en trámite', 3, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(130, 40.362, -3.58938, 87150230, 'Alquiler de Ático en avenida de la Gran Vía del Sureste, 33', 'Particular    juan ignacio', '\"Ático en alquiler, dormitorio matrimonio, salón 15 m, cocina independiente, terraza 16 m, amueblado. Garaje, trastero y piscina. Calefacción y aire acondicionado. Ideal parejas.\"', 0, '609 201 897', 'piso', 720, '9.60', 'Avenida de la Gran Vía del Sureste, 33, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 75, 0, 1, 0, 0, 0, 0000, 0, '', '', 7, 0, 0, 0, '2019-09-30', 'Avenida de la Gran Vía del Sureste, 33', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 65, 0, 0, 0, 0),
(131, 40.3632, -3.58741, 86744549, 'Alquiler de Piso en Arte Pop, 8', 'Profesional   Vivenio Madrid', '\"¡OFERTA \"VUELTA AL COLE\", LLÉVATE EL PRIMER MES GRATIS!Vivienda de 2 dormitorios. Calle Arte pop 8, está ubicada en el PAU de Vallecas, un nueva área residencial dentro de Madrid con amplias zonas verdes, parques, centros docentes, complejos deportivos, espacios sociales, un gran centro comercial y numerosas calles peatonales. una inteligente distribución de las viviendas, aprovechando los espacios lo mejor posible. Excelentes calidades y sus zonas comunes hacen de arte pop 8 un lugar ideal para vivir, piscina, zona de juegos, que incluyen plaza de garaje y trastero. Consulte condiciones y disponibilidad. Sin comisiones de agencia.Vivienda no amueblada.REQUISITOS 1 mes de fianza + seguro de impago.Contrato indefinido de más de un año de antigüedad.Seguro de vivienda (contenido). \".\"', 0, '917 222 018', 'piso', 850, '10.90', 'Arte Pop, 8, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 78, 2, 2, 0, 0, 0, 2010, 0, '', '', 7, 0, 0, 0, '2019-10-02', 'Arte Pop, 8', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(132, 40.3625, -3.60031, 87162961, 'Alquiler de Piso en Ensanche de Vallecas - La Gavia', 'Profesional   Federico Villegas Lamberti', '\"Se alquila vivienda amplia y muy luminosa en urbanización cerrada con piscina, paddle, zona infantil y vigilancia 24 horas los 365 días del año. La vivienda está completamente amueblada, compuesta por 3 habitaciones espaciosas, 2 baños completos (uno de ellos en suite con bañera y el otro con plato de ducha), gran salón comedor y cocina amueblada y equipada con todos los electrodomésticos, con terraza tendedero. Dispone de aire acondicionado en todas las estancias y calefacción de gas natural individual. Ventanas de climalit y suelo de tarima. Cuenta con armarios empotrados en los dormitorios y 3 adicionales en el pasillo y entradita, con lo cual hay mucha capacidad de almacenamiento.La vivienda se alquila junto con una plaza de garaje en el mismo edificio. En los alrededores podrás encontrar zonas para niños, comercio y centro comercial la Gavia a 5 minutos. Bien comunicado en cuanto a transporte público (Metro Las Suertes, paradas de autobús diurno y nocturno en la misma puerta) y fácil acceso a carreteras M45, M50 y A3.Mejor ver. Para más información y visitas contactar con Patricia en el 699_323_303 (también atiendo WhatsApp).\"', 0, '914 879 865', 'piso', 1200, '9.60', ', Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 125, 3, 2, 0, 0, 0, 0000, 0, 'gas natural', '', 1, 0, 0, 0, '2019-10-01', '', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 105, 0, 0, 0, 0),
(133, 40.3632, -3.58741, 85314514, 'Alquiler de Ático en calle de Arte Pop, 8', 'Profesional   Vivenio Madrid', '\"¡OFERTA \"VUELTA AL COLE\", LLÉVATE EL PRIMER MES GRATIS!Vivienda de 2 dormitorios con DOS FANTÁSTICAS TERRAZASCalle Arte pop 8, está ubicada en el PAU de Vallecas, un nueva área residencial dentro de Madrid con amplias zonas verdes, parques, centros docentes, complejos deportivos, espacios sociales, un gran centro comercial y numerosas calles peatonales. una inteligente distribución de las viviendas, aprovechando los espacios lo mejor posible. Excelentes calidades y sus zonas comunes hacen de arte pop 8 un lugar ideal para vivir, piscina, zona de juegos, que incluyen plaza de garaje y trastero. Consulte condiciones y disponibilidad. Sin comisiones de agencia.Vivienda no amueblada. REQUISITOS 1 mes de fianza + seguro de impago.Contrato indefinido de más de un año de antigüedad.Seguro de vivienda (contenido).\"', 0, '917 222 018', 'piso', 1175, '15.26', 'Calle de Arte Pop, 8, Urb. Edificio Arte Pop, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 77, 2, 2, 0, 0, 0, 2010, 0, 'gas natural', '', 7, 0, 0, 0, '2019-10-01', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(134, 40.3695, -3.61411, 87166508, 'Alquiler de Piso en avenida de la Gavia, 39', 'Profesional   Alquiler Seguro, S.A.U.', '\"Apartamento de obra nueva de 50 m2, 1 dormitorio, salón con cocina americana completamente amueblada y equipada, 1 baño completo, armarios empotrados, calefacción individual, aire acondicionado por conducto, exterior y muy luminoso, se entrega amueblado. Gastos de comunidad y plaza de garaje incluidos en el precio. Finca con ascensor, piscina, jardines, instalaciones deportivas, portería. Zona con todos los servicios a 5 minutos del C. C. \"La Gavia\". Junto al Metro: \"La Gavia\"(L1). Líneas EMT: 145-N9. No se aceptan animales.\"', 0, '902 375 777', 'piso', 695, '13.90', 'Avenida de la Gavia, 39, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 50, 0, 1, 0, 0, 0, 0000, 0, '', '', 5, 0, 0, 0, '2019-10-01', 'Avenida de la Gavia, 39', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(135, 40.3632, -3.58741, 87171405, 'Alquiler de Piso en Arte Pop, 8', 'Profesional   Vivenio Madrid', '\"¡Alquila ahora y llévate el primer mes gratis!Vivienda de 1 dormitorio en 2ª planta. Calle Arte pop 8, está ubicada en el PAU de Vallecas, un nueva área residencial dentro de Madrid con amplias zonas verdes, parques, centros docentes, complejos deportivos, espacios sociales, un gran centro comercial y numerosas calles peatonales. una inteligente distribución de las viviendas, aprovechando los espacios lo mejor posible. Excelentes calidades y sus zonas comunes hacen de arte pop 8 un lugar ideal para vivir, piscina, zona de juegos, que incluyen plaza de garaje y trastero. Consulte condiciones y disponibilidad. Sin comisiones de agencia.Vivienda no amueblada.REQUISITOS 1 mes de fianza + seguro de impago.Contrato indefinido de más de un año de antigüedad.Seguro de vivienda (contenido).\"', 0, '917 222 018', 'piso', 695, '14.48', 'Arte Pop, 8, Urb. Edificio Arte Pop, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 48, 0, 1, 0, 0, 0, 0000, 0, 'gas natural', 'en trámite', 2, 0, 0, 0, '2019-10-02', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(136, 40.3721, -3.63043, 87168846, 'Alquiler de Piso en bulevar de la Naturaleza, 20', 'Particular    ROSA', '\"La calefacción, el agua caliente y la plaza de garaje están incluidos en el precio del alquiler. Edificio de 10 años, segundo piso exterior. Muy luminoso de techos altos. Sol de mañana.Cocina completa con encimera de silestone. Salón, el recibidor y baño amueblados. Armarios empotrados. Pre-instalación aire acondicionado.Dispone de una terraza tendedero con espacio de almacenaje.Suelo de tarima.\"', 0, '650 132 837', 'piso', 730, '10.43', 'Bulevar de la Naturaleza, 20, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 70, 2, 1, 0, 0, 0, 0000, 0, '', '', 2, 0, 0, 0, '2019-10-02', 'Bulevar de la Naturaleza, 20', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 0),
(137, 40.371, -3.62992, 34529083, 'Alquiler de Piso en calle de Honrubia s/n', 'Profesional   MAGNUM', '\"770€. Bonitas viviendas 2 dormitorios, que incluyen plaza de garaje y trastero. En perfecto estado de alquiler, cuenta con cocina amueblada con encimera, horno, fregadero y campana. El edificio se caracteriza por su innovador y arquitectura vanguardista, amplias zonas comunes ajardinadas.Muy cercana al Centro de Salud del Ensanche de Vallecas, en dónde se puede encontrar comercios y servicios como Mercadona (en la puerta), farmacia, gimnasio, bancos y gasolinera. Además, con el Instituto Villa de Vallecas y Centro de Alzheimer Fundación Reina Sofía a 250 metros. Con fácil acceso desde el Polígono de Vallecas y M-40/M-45 (a 3 minutos), A-3 (a 5 minutos). Comunicado mediante transporte de autobús y con parada de metro \"Congosto\" cercana. Horario de atención telefonica de 9:00 A 21:00.Gastos de IBI aparte. No pagas los gastos de comunidad durante los primeros 3 años e IBI durante los primeros 2 años ¡SIN COMISION DE AGENCIA! Aprovecha esta oportunidad única.SÓLO SE PIDE: MES DE FIANZA: 770€**Las imagenes corresponden a un apartamento tipo.**Viviendas sujetas a disponibilidad.Para alquilar una vivienda con Fidere, la renta total de la vivienda no puede superar el 40% de los ingresos mensuales netos del/los firmantes del contrato.\"', 0, '918 006 712', 'piso', 770, '11.49', 'Calle de Honrubia s/n, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 67, 2, 1, 0, 0, 0, 0000, 0, '', 'no indicado', 0, 0, 0, 0, '2019-10-01', 'Calle de Honrubia s/n', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138, 40.3673, -3.62094, 83207197, 'Alquiler de Piso en calle la Granja de San Ildefonso s/n', 'Profesional   MAGNUM', '\"980€. Bonitas viviendas de 2 dormitorios, reformadas a estrenar: cocina y baños nuevo, con acabados de lujo. En perfecto estado de alquiler, tarima flotante, cocina totalmente equipada con electrodomésticos de primera calidad, la vivienda incluye plaza de garaje y trastero. Urbanizacion cerrada, com amplias zonas comes ajardinadas, pista de pádel, zona infantil, para los más pequeños de la casa, y piscina exterior. Urbanización situada en zona residencial y consolidada del ensanche, a menos de 5 minutos del Centro de Salud Ensanche de Vallecas, escuela infantil Rayuela y Colegio Rodríguez Sahagún. Cercano al casco histórico con todos los servicios y comercios a mano. Acceso a M-45 y A-3 (ambos, a 2 minutos) y transporte público mediante autobús y parada de metro \"La Gavia\" a 600 metros.Horario de atención telefonica de 9:00 A 21:00.Gastos de IBI aparte. No pagas los gastos de comunidad durante los primeros 3 años e IBI durante los primeros 2 años ¡SIN COMISION DE AGENCIA! Aprovecha esta oportunidad única.SÓLO SE PIDE: MES DE FIANZA: 925€CONDICIONES DE LA OFERTA DE BIENVENIDA:1. Permanencia de al menos un año en la vivienda desde la firma del contrato.2. Durante primer año de contrato (i) se encuentre en todo momento al corriente en el pago de la renta y gastos y (ii) cumpla con el resto de las obligaciones que se pacten en el contrato.Caso de no cumplir con lo anterior: la OFERTA DE BIENVENIDA quedará automáticamente sin efecto con carácter retroactivo y el arrendatario deberá devolver el importe correspondiente a la promoción aplicada.**Las imagenes corresponden a un apartamento tipo.**Viviendas sujetas a disponibilidad.Características básicas85 m² construidos2 habitación2 bañosSegunda mano/buen estadoCasa sin amueblarCertificación energética: (IPE no indicado) EdificioPlanta 3ª exterior Con ascensor  EquipamientoAire acondicionadoPara alquilar una vivienda con Fidere, la renta total de la vivienda no puede superar el 40% de los ingresos mensuales netos de la unidad familiar. Horario de atención telefonica de 9:00 A 21:00.\"', 0, '918 006 712', 'piso', 980, '9.61', 'Calle la Granja de San Ildefonso s/n, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 102, 2, 2, 0, 0, 0, 0000, 0, '', 'no indicado', 3, 0, 0, 0, '2019-10-01', 'Calle la Granja de San Ildefonso s/n', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 0),
(139, 40.3596, -3.59507, 85288662, 'Alquiler de Piso en calle Embalse de Pinilla, 51', 'Particular    amaya', '', 0, '', 'piso', 2000, '33.33', 'Calle Embalse de Pinilla, 51, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 60, 2, 1, 0, 0, 0, 0000, 0, '', 'en trámite', 5, 0, 0, 0, '0000-00-00', 'Calle Embalse de Pinilla, 51', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 55, 0, 0, 0, 0);
INSERT INTO `viviendas` (`id`, `latitud`, `longitud`, `id_vivienda`, `titulo`, `anunciante`, `descripcion`, `reformado`, `telefonos`, `tipo`, `precio`, `precio_metro`, `direccion`, `provincia`, `ciudad`, `metros_cuadrados`, `habitaciones`, `baños`, `parking`, `segunda_mano`, `armarios_empotrados`, `construido_en`, `amueblado`, `calefaccion_individual`, `calefaccion_energetica`, `planta`, `exterior`, `interior`, `ascensor`, `fecha`, `calle`, `barrio`, `distrito`, `terraza`, `trastero`, `cocina_equipada`, `cocina_equipada2`, `aire_acondicionado`, `piscina`, `jardin`, `metros_cuadrados_utiles`, `movilidad_reducida`, `plantas`, `mascotas`, `balcon`) VALUES
(140, 40.3663, -3.60001, 39497373, 'Alquiler de Piso en calle José Tamayo s/n', 'Profesional   MAGNUM', '\"740€. Bonitas viviendas de 1 dormitorios, reformadas a estrenar: cocina y baños nuevo, con acabados de lujo. En perfecto estado de alquiler, suelo parqué, armarios empotrados, luminarias nuevas y cocina totalmente equipada con electrodomésticos de primeras marcas. La vivienda incluye en el precio plaza de garaje y trastero. Promoción de viviendas en el Ensanche de Vallecas a 20 metros de C. C. La Gavia. Acceso directo e inmediato a la M-45 y A-3 (1 minuto para ambos). Metro Las Suertes a 150 metros. Gran oferta de ocio: La Gavia, IKEA, Carrefour, Cinesa, etc. Junto al colegio Gredos San Diego. Sus servicios, sus comunicaciones, sus parques y su cercanía al centro de Madrid hacen de la promoción un lugar único para vivir en viviendas de reciente construcción con todos los equipamientos y servicios.SÓLO SE PIDE: MES DE FIANZA: 740€Gastos de IBI aparte. No pagas los gastos de comunidad durante los primeros 3 años e IBI durante los primeros 2 años ¡SIN COMISION DE AGENCIA! Aprovecha esta oportunidad única.**Las imagenes corresponden a un apartamento tipo.**Viviendas sujetas a disponibilidad.\"', 0, '918 006 712', 'piso', 740, '16.44', 'Calle José Tamayo s/n, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 45, 0, 1, 0, 0, 0, 0000, 0, '', 'no indicado', 4, 0, 0, 0, '2019-10-01', 'Calle José Tamayo s/n', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(141, 40.3702, -3.60686, 2107565, 'Alquiler de Piso en calle Entrepeñas, 62', 'Particular    Juan', '\"Particular alquila piso muy luminoso, todo exterior, estupendas vistas, amplio, nuevo en Ensanche de Vallecas, Metro La Gavia. Consta de 3 dormitorios con armarios empotrados, 2 baños, amplio salón, cocina con lavadora, frigorífico, horno, placa vitrocerámica y campana extractora. Parquet y ventanas Climalit. Con terraza/ tendedero. Amueblado y también sin muebles.Solo 8 vecinos por portal y 2 vecinos por planta, zona tranquila, en urbanización cerrada con zona infantil de juegos. Conserje en la puerta.Metro y bus cerca en la puerta. A 200m del Ikea, Carrefour y Centro Comercial La Gavia, salidas inmediatas a M45 y A3. Garaje y Trastero incluidos. IBI e impuesto basura incluidos.Lo alquila directamente el dueño, sin comisión de agencias. Disponible inmediatamente.La casa dispone de portero automático\"', 0, '630 423 796', 'piso', 1300, '10.83', 'Calle Entrepeñas, 62, Urb. Los cisnes, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 120, 3, 2, 0, 0, 0, 0000, 0, '', 'no indicado', 1, 0, 0, 0, '2019-08-07', '', '', '', 0, 0, 0, 0, 0, 0, 0, 110, 0, 0, 0, 0),
(142, 40.371, -3.62992, 34529075, 'Alquiler de Piso en calle de Honrubia s/n', 'Profesional   MAGNUM', '\"850€. Bonitas viviendas 3 dormitorios, que incluyen plaza de garaje y trastero. En perfecto estado de alquiler, cuenta con cocina amueblada con encimera, horno, fregadero y campana. El edificio se caracteriza por su innovador y arquitectura vanguardista, amplias zonas comunes ajardinadas.Muy cercana al Centro de Salud del Ensanche de Vallecas, en dónde se puede encontrar comercios y servicios como Mercadona (en la puerta), farmacia, gimnasio, bancos y gasolinera. Además, con el Instituto Villa de Vallecas y Centro de Alzheimer Fundación Reina Sofía a 250 metros. Con fácil acceso desde el Polígono de Vallecas y M-40/M-45 (a 3 minutos), A-3 (a 5 minutos). Comunicado mediante transporte de autobús y con parada de metro \"Congosto\" cercana. Horario de atención telefonica de 9:00 A 21:00.Gastos de IBI aparte. No pagas los gastos de comunidad durante los primeros 3 años e IBI durante los primeros 2 años ¡SIN COMISION DE AGENCIA! Aprovecha esta oportunidad única.SÓLO SE PIDE: MES DE FIANZA: 850€**Las imagenes corresponden a un apartamento tipo.**Viviendas sujetas a disponibilidad.Para alquilar una vivienda con Fidere, la renta total de la vivienda no puede superar el 40% de los ingresos mensuales netos del/los firmantes del contrato.\"', 0, '918 006 712', 'piso', 850, '9.24', 'Calle de Honrubia s/n, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 92, 3, 2, 0, 0, 0, 0000, 0, '', 'no indicado', 0, 0, 0, 0, '2019-10-01', 'Calle de Honrubia s/n', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(143, 40.3566, -3.59048, 85967307, 'Alquiler de Piso en calle la Escuela de Vallecas', 'Profesional   MAGNUM', '\"790€Moderna promocion de viviendas, muy luminoso, reformado a estrenar: cocina y baños nuevo, con acabados de lujo. En perfecto estado de alquiler, tarima flotante, armarios empotrados, la cocina está totalmente equipada con electrodomésticos de primera calidad: frigorifico, lavadora, lavavajillas, microondas... Las viviendas incluyen plaza de garaje. Urbanización privada con servicio de portería, zonas comunes ajardinadas y piscina exteriorCuenta con óptimas comunicaciones, situada junto a la autopista A-3 y M-45. Metro: Línea 1 y de las diferentes líneas de autobús. Amplia variedad de centros educativos. Ubicado a pocos metros se sitúa el Centro Comercial La Gavia con amplia diversidad de tiendas, cines, restaurantes, además de Carrefour e Ikea. La zona dispone de Centro Salud y de Hospital, en definitiva, con todos los servicios que uno puede necesitar a la puerta de su vivienda.Horario de atención telefonica de 9:00 a 21:00SÓLO SE PIDE: MES DE FIANZA: 790No pagas los gastos de comunidad durante los primeros 3 años e IBI durante los primeros 2 años ¡SIN COMISION DE AGENCIA! Ni honorarios de comercialización para el inquilino. Aprovecha esta oportunidad única. **Las imágenes corresponden a un apartamento tipo.**Viviendas sujetas a disponibilidad. \".\"', 0, '912 031 514', 'piso', 750, '13.64', 'Calle la Escuela de Vallecas, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 55, 0, 1, 0, 0, 0, 0000, 0, '', 'no indicado', 4, 0, 0, 0, '2019-10-01', 'Calle la Escuela de Vallecas', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 0),
(144, 40.3607, -3.59421, 86099244, 'Alquiler de Piso en avenida ensanche de Vallecas, 114', 'Particular    particular', '\"ideal para familia, 2 meses de fianza mayor información por whatpps 631160077. imprescindible demostrar solvencia económica.\"', 0, '', 'piso', 1050, '8.40', 'Avenida ensanche de Vallecas, 114, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 125, 3, 2, 0, 0, 0, 0000, 0, 'gas natural', 'en trámite', 4, 0, 0, 0, '0000-00-00', 'Avenida ensanche de Vallecas, 114', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(145, 40.3724, -3.63115, 86465903, 'Alquiler de Piso en Ensanche de Vallecas - La Gavia', 'Profesional   Torresrubí gestión inmobiliaria', '\"A pocos minutos de la vivienda encontrarás bares, bazares, gasolineras, supermercados, restaurantes…  Y si lo que te gusta es disfrutar de la naturaleza encontrarás los parques ¨Navamores¨, ¨Las cataratas¨ y el parque ¨la gavia¨. Y si eres de las personas que te encanta hacer deporte tienes el ¨gimnasio callejero¨, perfecto para hacer tus deportes favoritos y disfrutar al aire libre. A unos minutos de la vivienda podrás coger el metro de congosto para ir a cualquier destino, pero si pefieres más el autobús tienes para elegir entre el 103,142 y 54. Para ir en coche tienes el acceso a la avenida Mayorazgo, la carretera de Villaverde a Vallecas, la M-40 y la M-45.  La vivienda tiene 4 habitaciones 3 de ellas simples y otra doble, 2 baños, salón, cocina, garaje y trastero. Unica vivienda en planta   No dude en ponerse en contacto con nosotros para cualquier consulta y para realizar una visita.\"', 0, '918 003 827', 'piso', 1050, '6.77', ', Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 155, 4, 2, 0, 0, 0, 2007, 0, 'gas natural', 'en trámite', 6, 0, 0, 0, '2019-09-20', '', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0),
(146, 40.3797, -3.63301, 36065039, 'Alquiler de Piso en calle Calle Puerto de Pozazal, 37', 'Profesional   Contacto Contacto', '\"LEER TEXTO COMPLETO  No pedimos AVALES bancarios, pedimos contrato de trabajo y 2 ultimas nominas, se puede entrar cualquier día del mes, desde el día que entra se pagaría cada 30 días. Se encuentra ubicado en la calle puerto de pozazal 37, en el ensanche de vallecas, metro y renfe mas cercano sierra de guadalupeAl alquiler del apartamento se le incluye: gimnasio, piscina, pádel, parque infantil, comunidad, ascensores, agua sin limitación y hasta 50 € de luz ya incluidos en el precio. Autobuses, renfe y metro sierra de Guadalupe. También tenemos en otras zonas. NO SE ADMITEN MASCOTAS.Teléfono de contacto 622843044.\"', 0, '912 173 875', 'piso', 750, '13.64', 'Calle Calle Puerto de Pozazal, 37, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 55, 0, 1, 0, 0, 0, 0000, 0, '', 'en trámite', 3, 0, 0, 0, '2019-10-01', 'Calle Calle Puerto de Pozazal, 37', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0),
(147, 40.3605, -3.59392, 83602553, 'Alquiler de Piso en avenida Ensanche de Vallecas, Madrid, 116', 'Profesional   Témpore Homes', '\"¡Alquila ahora y llévate el primer mes gratis!Vivienda de 1 dormitorio, situada en el Ensanche de Vallecas, muy próxima al Centro Comercial de La Gavia, Ikea, y en el tramo medio del barrio, junto a M45, y frente a metro de Valdecarros, a escasos 100 metros. La urbanización dispone de control de acceso, zonas ajardinadas, sala comunitaria, dos piscinas (adulto y niños), servicio de conserjería.Edificio singular, con estructura y diseño moderno, de reciente construcción, con plaza de garaje y trastero.Consulte condiciones y disponibilidad.Las viviendas se alquilan no amuebladas. Imágenes pertenecen a vivienda piloto sin carácter contractual.Aire acondicionado opcional. \".REQUISITOSAportación de 3 últimas nóminas o similar para acreditar ratio de solvenciaContrato indefinido o similar con antigüedad mínima de 1 año.En la firma de contrato se solicitará un seguro de vivienda de contenido1 mes de fianza + Seguro de Impago.\"', 0, '917 222 005', 'piso', 780, '13.00', 'Avenida Ensanche de Vallecas, Madrid, 116, Urb. Edificio Vallecas 114, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 60, 0, 1, 0, 0, 0, 2011, 0, 'gas natural', '', 1, 0, 0, 0, '2019-09-27', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(148, 40.3605, -3.59392, 82407813, 'Alquiler de Piso en avenida del Ensanche de Vallecas, Madrid, 116', 'Profesional   Témpore Homes', '\"¡Alquila ahora y llévate el primer mes gratis!TÉMPORE HOMES ofrece viviendas a estrenar de 1 (baño más un aseo), situadas en el Ensanche de Vallecas, muy próxima al Centro Comercial de La Gavia, Ikea, y en el tramo medio del barrio, junto a M45, y frente a metro de Valdecarros, a escasos 100 metros. La urbanización dispone de control de acceso, zonas ajardinadas, sala comunitaria, dos piscinas (adulto y niños), servicio de conserjería.Edificio singular, con estructura y diseño moderno, de reciente construcción, con plaza de garaje y trastero.Consulte condiciones y disponibilidad.Las viviendas se alquilan no amuebladas.Aire acondicionado opcional. El precio de la vivienda varía en función de la planta escogida.REQUISITOSAportación de 3 últimas nóminas o similar para acreditar ratio de solvenciaContrato indefinido o similar con antigüedad mínima de 1 año.En la firma de contrato se solicitará un seguro de vivienda de contenido1 mes de fianza + Seguro de Impago.\"', 0, '917 222 005', 'piso', 790, '13.39', 'Avenida del Ensanche de Vallecas, Madrid, 116, Urb. Edificio Vallecas 114, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 59, 0, 1, 0, 0, 0, 0000, 0, '', '', 3, 0, 0, 0, '2019-09-27', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(149, 40.377, -3.61013, 86746312, 'Alquiler de Chalet pareado en puente del Arzobispo, 14', 'Particular    javier', '\"Chalet en una de las mejores zona de Madrid. Junto a la ciudad deportiva del Rayo Vallecano.Casa de tres plantas. Con 5 habitaciones y tres baños.Planta baja: cocina, salón, una habitación y pequeño baño con ducha. Primera planta: cuatro habitaciones y dos baños (uno en el dormitorio principal)Planta sotano: garaje para varios coches. Espacio completamente diáfano.Sistema de calefacción y airea condicionado por suelo radiante en toda la casa.Sistema de alarma e internet en todas las habitaciones.\"', 0, '639 079 907', 'chalet', 2800, '9.33', 'Puente del Arzobispo, 14, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 300, 5, 3, 0, 0, 0, 0000, 0, '', '', 0, 0, 0, 0, '0000-00-00', 'Puente del Arzobispo, 14', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0),
(150, 40.3599, -3.58866, 86751545, 'Alquiler de Piso en calle la Escuela de Vallecas, 20', 'Particular    Benjamin', '\"Se alquila piso seminuevo de 75m2 habitables, distribuidos en 2 dormitorios con armarios empotrados y ventanas amplias, espacioso salón independiente con mirador, cocina con tendedero cerrado, 2 baños (uno de ellos en la habitación principal) y sin amueblar.También se incluye en el precio plaza de garaje de 13m2 y trastero de 5m2.Dispone de preinstalación de aire acondicionado canalizable y suelo radiante. Muy buenas calidades, luminoso, con orientación noroeste. Vivienda con 11 años de antigüedad cuenta con ascensor, situada dentro de una urbanización cerrada con zonas comunes y con conserje. Zona con todo tipo de servicios próximos: Centro Comercial La Gavia, colegios, instalaciones deportivas municipales etc y situado a 150 metros de la salida de Metro de “Valdecarros”, autobuses cercanos y con magnífica comunicación para coche con acceso a la A3, M45, M50.PRECIO DEL ALQUILER CON COMUNIDAD INCLUIDA.\"', 0, '', 'piso', 900, '6.98', 'Calle la Escuela de Vallecas, 20, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 129, 2, 2, 0, 0, 0, 0000, 0, '', 'no indicado', 3, 0, 0, 0, '2019-09-30', 'Calle la Escuela de Vallecas, 20', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 75, 0, 0, 0, 0),
(151, 40.3664, -3.59748, 86788600, 'Alquiler de Ático en avenida de las Suertes, 55', 'Particular    Ali', '\"Se alquila ático con magníficas vistas. Tiene dos habitaciones y dos baños. Se puede alquilar sin amueblar o amueblado. Situado en la Avenida de Las Suertes 55, al lado del Centro Comercial La Gavia, metro Las Suertes. Piscina de verano, piscina de invierno, pádel acristalado, zona infantil, amplios jardines comunitarios, casa climatizada A/A y calefacción, gimnasio completo, spa, sauna muy amplia, vigilancia 24 horas, a 50 metros centro comercial y cines, a 300 metros línea 1 de metro, autobuses nocturnos, 2 amplios armarios empotrados, vistas a la sierra norte de Madrid, mirador con persiana instalada, toallero eléctrico en el baño, garaje muy amplio sin problemas de maniobrabilidad. \".REQUISITOS 1 mes de fianza + seguro de impago.Contrato indefinido de más de un año de antigüedad.\"', 0, '601 061 677', 'piso', 1295, '12.33', 'Avenida de las Suertes, 55, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 105, 2, 2, 0, 0, 0, 0000, 0, '', 'inmueble exento', 9, 0, 0, 0, '2019-09-13', 'Avenida de las Suertes, 55', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(152, 40.3636, -3.58727, 86802763, 'Alquiler de Piso en calle Arte Conceptual', 'Profesional   Federico Villegas Lamberti', '\"Coqueto apartamento que consta de salón- comedor, cocina con terraza tendedero, dos dormitorios y 2 baños. Amueblado y equipado con electrodomésticos. Plaza de garaje incluida en el precio del alquiler. Mejor verlo! Para más información contactar con Patricia en el 699_323_303 (también atiendo WhatsApp).\"', 0, '914 879 865', 'piso', 1025, '11.39', 'Calle Arte Conceptual, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 90, 2, 2, 0, 0, 0, 0000, 0, 'TRUE', '', 3, 0, 0, 0, '2019-09-04', 'Calle Arte Conceptual', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(153, 40.3562, -3.59433, 86805660, 'Alquiler de Ático en Ensanche de Vallecas - La Gavia', 'Profesional   Inmobiliarias Madrid XXI', '\"Precioso ático de un dormitorio amplio, con gran salón y cocina independiente, Increíble terraza 85 METROS CUADRADOS, luminoso piso, con plaza de garaje, y piscina. Inmejorables vistas. Urbanización privada con portero, y zonas comunes con una buena piscina. Cerca del metro Valdecarros al lado del centro comercial La Gavia y muy cerca de la Ciudad Deportiva del Rayo Vallecano. Baño con ventana exterior, tan difícil de encontrar, El piso está sin muebles, aunque no tendría inconveniente en ponerlos si es un buen perfil de cliente, . Lo que sí está amueblada es la cocina y dotada con nevera combi, lavaplatos, horno, extractora, placa vitrocerámica y lavadora. Las orientaciones son este, oeste y norte.  Lo alquilaría con plaza de garaje. ¡ Te va a encantar, ven a verlo, puede ser tu hogar! Imprescindible buena documentación para alquilarlo.\"', 0, '912 177 843', 'piso', 850, '6.12', ', Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 139, 0, 1, 0, 0, 0, 2007, 0, 'gas natural', 'no indicado', 8, 0, 0, 0, '2019-09-05', '', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 54, 0, 0, 0, 0),
(154, 40.3745, -3.6325, 86029073, 'Alquiler de Estudio en carretera de Villaverde a Vallecas', 'Profesional   sanmial .', '\"Amplio apto turística de 46m2. Dispone de dormitorio (NO INDEPENDIENTE), mueble separatorio en salón, cocina americana equipada, cuarto de baño completo con bañera. Armario empotrado a la entrada de vivienda. Aire acondicionado con bomba de calor. Gran ventanal, lo que proporciona mucha luminosidad a la vivienda. Terraza exterior en salón. Plaza de garaje incluida en precio. Urbanización con piscina, zona verde y Conserje físico 24h. Autoservicio lavandería \"A escasos 8 minutos caminando de Metro Sierra de Guadalupe y estación de Renfe. \".\"', 0, '918 003 216', 'piso', 550, '11.96', 'Carretera de Villaverde a Vallecas, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 46, 0, 1, 0, 0, 0, 0000, 0, '', 'en trámite', 3, 0, 0, 0, '2019-09-30', 'Carretera de Villaverde a Vallecas', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(155, 40.3721, -3.61208, 86877972, 'Alquiler de Piso en calle Barranco del Novillo, 16', 'Particular    Estibaliz', '\"Abstenerse Agencias / Inmobiliarias. Disponible en Noviembre 2019.ABSTENERSE AGENCIAS/INMOBILIARIAS! . Piso semi-nuevo con pocos años de antigüedad en perfectas condiciones, gran salón de 28 m2, 2 habitaciones, 1 baño amueblado completo con mampara, cocina amueblada con encimera de silestone, vitroceramica, horno, lavadora y lavavajillas, tendedero cerrado acristalado, A/A por conductos internos en toda la casa, 3 armarios empotrados dobles, suelos de parquet, puerta acorazada, 1 PLAZA DE GARAJE, amplio trastero. 4º planta con ascensor. Urbanización dotada de piscina, gimnasio, salón social, portero físico y cámaras de seguridad 24 horas.Condiciones: Fianza de 2 mensualidades y seguro cobros/3ª mensualidad fianza. distribución: 3 vecinos en el edificio la casa dispone de: portero automático.\"', 0, '', 'piso', 925, '10.28', 'Calle Barranco del Novillo, 16, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 90, 2, 1, 0, 0, 0, 2008, 0, 'gas natural', 'en trámite', 6, 0, 0, 0, '2019-09-25', 'Calle Barranco del Novillo, 16', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 75, 0, 0, 0, 0),
(156, 40.3645, -3.58329, 1670450, 'Alquiler de Dúplex en calle Cerro del Murmullo, 13', 'Particular    antonio', '\"mi tel es 670 06 07 90 duplex precioso, dos dormitorios amueblado con cama de matrimonio cada uno y dos cuartos de baño, muy cerca del Ikea Vallecas y amueblado con muebles de IKea, Techos altos. escalera de diseño, cocina independiente con lavadora, lavavajillas, nevera, microondas, vitrocerámica todo a estrenar. vigilancia 24 h, plaza de garaje grande, Edificio moderno de 2008, fachada de cristal, jardines con césped, piscina. muy bien comunicado con el metro, la m-45 y el aeropuerto. Mi tel es 670 06 07 90.\"', 0, '669 445 028', 'piso', 1000, '12.50', 'Calle Cerro del Murmullo, 13, Urb. jardines del valle, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 80, 2, 2, 0, 0, 0, 0000, 0, '', 'en trámite', 1, 0, 0, 0, '2019-09-23', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(157, 40.3645, -3.58329, 1668062, 'Alquiler de Estudio en calle Cerro del Murmullo, 13', 'Particular    cristina', '\"Mi tel es 670 06 07 90 alquilo duplex precioso, muy próximo a Ikea del PAU de Vallecas, amueblado con muebles de Ikea, muy luminoso, cocina cerrada con ventana pasaplatos y equipada con electrodomésticos: lavadora, lavavajillas, nevera, microondas. Precioso desde la planta de arriba ves la doble altura del salón y queda muy diáfano, con grandes cristaleras, aire acondicionado frío/calor, tarima flotante, salones comunes, vigilancia 24 h, plaza de garaje, piscina, jardines césped, fachada del edificio de cristal, muy bien comunicado metro a 10 minutos, A-3 y M-40. 60 metros. Enfrente tiene la vía verde de la Comunidad de Madrid, con un pinar precioso pista para correr y montar en bici. distribución: 20 vecinos en el edificio.\"', 0, '670 060 790', 'piso', 950, '14.62', 'Calle Cerro del Murmullo, 13, Urb. jardines del valle, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 65, 0, 1, 0, 0, 0, 0000, 0, 'TRUE', 'no indicado', 1, 0, 0, 0, '2019-09-17', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(158, 40.3756, -3.61003, 38756710, 'Alquiler de Piso en calle de Villamayor de Santiago, 11', 'Particular    Javier montero', '\"Calefacción caldera de gas.\"', 0, '', 'piso', 1200, '14.12', 'Calle de Villamayor de Santiago, 11, Barrio Ensanche de Vallecas - La Gavia, Distrito Villa de Vallecas, Madrid, Madrid capital, Madrid', 'Madrid capital, Madrid', 'Madrid', 85, 2, 2, 0, 0, 0, 0000, 0, 'gas natural', 'no indicado', 5, 0, 0, 0, '2019-09-29', 'Calle de Villamayor de Santiago, 11', ' Barrio Ensanche de Vallecas - La Gavia ', ' Distrito Villa de Vallecas ', 0, 0, 0, 0, 0, 0, 0, 65, 0, 0, 0, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `viviendas`
--
ALTER TABLE `viviendas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `viviendas`
--
ALTER TABLE `viviendas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=159;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
